### ISSUE TITLE
https://odata.github.io/odatacpp-server is 404

### ISSUE THREAD

**Issue by chandruxp** [OData/odatacpp-server#1]
Hi there,

I was looking for the docs of this library. But the linked Github pages does not seem to work?

Thanks

**Comment by lewischeng-ms** [comment]
Sorry for that. The link is just a placeholder but currently we don't have plan on docs of this library. If you are seeking for example of writing a service, please visit the service projects under 'msvc\vs12\test_only' for reference (they are just primitive prototypes). If you have questions, please directly ask us here and we will be pleased to answer.

**Comment by chandruxp** [comment]
ok Thanks..
