### ISSUE TITLE
edm_model_writer::write_model() doesn't seem to produce correct XML metadata

### ISSUE THREAD

**Issue by cberge** [OData/odatacpp-server#19]
After fixing linux code in order to support prefix and namespace in xmlhelpers.cpp 
(see pull request  #18) I am wondering about edm_model_writer::write_model() and edm_model_writer::write_schema()

I may be wrong, but I had to make some changes in edm_model_writer.cpp in order to:
1) pass successfully the test on http://pragmatiqa.com/xodata/#
2) successfully connect Excel + Power Query to my Linux server through odata

Take a look to edm_model_writer::write_model():
It start with the following calls:
    write_start_element(U("Edmx"), U("edmx"));
    write_attribute_string(U("xmlns"), U("edmx"), U(""), U("http://docs.oasis-open.org/odata/ns/edmx"));
    write_attribute_string(U(""), U("Version"), U(""), model->get_version());

Take a look to write_start_element(U("Edmx"), U("edmx"));
From what I understand, write_start_element takes 2 args: 
    xml_writer::write_start_element(
            const string_t& elementName, 
            const string_t& namespaceName)

and just make a call to write_start_element_with_prefix(U(""), elementName, namespaceName);
which takes 3 arguments:
    xml_writer::write_start_element_with_prefix(
            const string_t& elementPrefix, 
            const string_t& elementName, 
            const string_t& namespaceName)

So, write_start_element(U("Edmx"), U("edmx"));
will resolve as (Edmx xmlns="edmx")
(Sorry, I replaced XML tag bracket per parenthesis as brackets content doesn't show...)

Both following write_attribute_string() calls are correct and the global result on Linux is:
(Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" xmlns="edmx" Version="4.0")

this xml element doesn't match those of the welknown example http://services.odata.org/V4/Northwind/Northwind.svc/$metadata below:
(edmx:Edmx Version="4.0" xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx")

Solution:

By simply replacing write_start_element(U("Edmx"), U("edmx")) 
by write_start_element_with_prefix(U("edmx"), U("Edmx"))
in edm_model_writer.cpp, I got this: 
(edmx:Edmx xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx" Version="4.0")
Which seems to be much more correct.

I got the same issue with
   write_start_element(U("DataServices"), U("edmx")); 
that should be
   write_start_element_with_prefix(U("edmx"), U("DataServices"));

and in edm_model_writer::write_schema():

write_start_element(U("Schema"), U("ns")); 
replaced by write_start_element(U("Schema")); 

write_attribute_string(U("xmlns"), U("ns"), U(""), U("http://docs.oasis-open.org/odata/ns/edm")); 
replaced by write_attribute_string(U(""), U("xmlns"), U(""), U("http://docs.oasis-open.org/odata/ns/edm"));

With these 4 changes, I succeed in passing tests and connecting to excel.
Being new to odata stuff, Maybe I'm missing something...
Can someone tell me if I'm wrong and why?
Thanks.

**Comment by lewischeng-ms** [comment]
Thanks for finding the issue. I think your perception is totally correct. We should have used XML prefix for those elements. Would you please send another PR for this?

**Comment by cberge** [comment]
Thanks for validation. I'll do this as soon as possible.
